spring:
  application:
    name: VPN-Service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  liquibase:
    enabled: false
    change-log: classpath:db/changelog-master.xml
  datasource:
    url: ${DB_URL}
    hikari:
      username: ${DB_USERNAME}
      driver-class-name: org.postgresql.Driver
      password: ${DB_PASSWORD}
      jdbc-url: ${DB_URL}
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterWrite=60m
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
logging:
  config: classpath:logback-spring.xml