spring:
  application:
    name: subscribe-link-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/vpn_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    enabled: false
    change-log: classpath:db/changelog-master.xml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#project:
#  vpn-panel-squad-uuid: ${VPN_PANEL_SQUAD_UUID}