spring:
  application:
    name: VPN-Service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/vpn_db}
    hikari:
      username: ${DB_USERNAME:postgres}
      driver-class-name: org.postgresql.Driver
      password: ${DB_PASSWORD:postgres}
      jdbc-url: ${DB_URL:jdbc:postgresql://postgres:5432/vpn_db}
  cache:
    caffeine:
      spec: maximumSize=500,expireAfterWrite=60m
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
logging:
  config: classpath:logback-spring.xml
project:
  origin-pattern: ${ORIGIN_PATTERN}
  dashboard-comment:
    min-score: 4.5
    min-length: 10
    limit: 5